server:
  port: 8081

spring:
  application:
    name: shop-context
  profiles:
    active: shop
  datasource:
    url: jdbc:mysql://localhost:3307/food_delivery_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: food_user
    password: food_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  
logging:
  level:
    harry.boilerplate.shop: DEBUG
    org.hibernate.SQL: DEBUG